/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package curvaabc.view;

import curvaabc.model.ConexaoDB;
import curvaabc.controller.ProdutoController;
import curvaabc.model.Produto;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan Victor
 */
public class AddProdutoView extends javax.swing.JFrame {
    
    //Conexão com o banco de dados
    Connection db_con;
    int row = -1;
    

    // Construtor
    public AddProdutoView() throws ClassNotFoundException {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    // Construtor
    public AddProdutoView(int i) throws ClassNotFoundException {
        initComponents();
        row = i;
        
        String id = (GerenciarProdutosView.tabelaGerenciar.getValueAt(row, 0)).toString();
        String preco = (GerenciarProdutosView.tabelaGerenciar.getValueAt(row, 1)).toString();
        String vendidos = (GerenciarProdutosView.tabelaGerenciar.getValueAt(row, 2)).toString();
        int criticidade = Integer.parseInt((GerenciarProdutosView.tabelaGerenciar.getValueAt(row, 3)).toString());
        
        input_id.setText(id);
        input_preco.setText(preco);
        input_quantidade.setText(vendidos);
        combo_criticidade.setSelectedIndex(criticidade-1);
        
    }
    
    public String corrigirStringPreco(String p){
        String preco = p;
        if (preco.contains(",")) preco = preco.replace(",", ".");
        return preco;
    }

    // Adiciona o produto no banco de dados
    private void adicionarProduto() throws SQLException, ClassNotFoundException{
        
        String id = input_id.getText();
        String preco = input_preco.getText();
        String quantidade = input_quantidade.getText();
        String criticidade = combo_criticidade.getSelectedItem().toString();
        Produto p = new Produto();
        // Recebe os valores dos inputs e põe em variáveis
        if(p.dadosOk(this, id, preco, quantidade, criticidade)){
            String preco_c = corrigirStringPreco(preco);
            p = p.criarProduto(id, preco_c, quantidade, criticidade);
        }
        
        ProdutoController p_controller = new ProdutoController();
        
       // Verifica corretude dos inputs
        if (p_controller.produtoOk(p)) {
            
            if (row > -1){
                p_controller.alterarProduto(this, p);
                row = -1;
            }
            else p_controller.adicionarProduto(this, p);

            // Resetar campos
            resetCampos();
        }       

        else {
            JOptionPane.showMessageDialog(AddProdutoView.this, "DADOS INVÁLIDOS \n\n Certifique-se de que seus valores são positivos");
        }
    }
    
    // Reseta os campos de input
    private void resetCampos(){
        input_id.setText("");
        input_preco.setText("");
        input_quantidade.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_id = new javax.swing.JTextField();
        input_preco = new javax.swing.JTextField();
        input_quantidade = new javax.swing.JTextField();
        combo_criticidade = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        button_adicionar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo_criticidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        combo_criticidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_criticidadeActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Preço");

        jLabel3.setText("Quantidade vendida");

        jLabel4.setText("Criticidade");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Adicionar / Editar produto");

        button_adicionar.setText("Salvar");
        button_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_adicionarMouseClicked(evt);
            }
        });

        button_cancelar.setText("Fechar");
        button_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(input_id)
                                    .addComponent(input_preco)
                                    .addComponent(input_quantidade)
                                    .addComponent(combo_criticidade, 0, 90, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 65, Short.MAX_VALUE)
                                .addComponent(button_adicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_cancelar))
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_criticidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_adicionar)
                    .addComponent(button_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_adicionarMouseClicked
        try {
            adicionarProduto();
        } catch (SQLException ex) {
            Logger.getLogger(AddProdutoView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddProdutoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_adicionarMouseClicked

    private void combo_criticidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_criticidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_criticidadeActionPerformed

    private void button_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cancelarMouseClicked

        AddProdutoView.this.dispose();
    }//GEN-LAST:event_button_cancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddProdutoView().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddProdutoView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_adicionar;
    private javax.swing.JButton button_cancelar;
    private javax.swing.JComboBox combo_criticidade;
    private javax.swing.JTextField input_id;
    private javax.swing.JTextField input_preco;
    private javax.swing.JTextField input_quantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
