/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package curvaabc.view;

import curvaabc.model.ConexaoDB;
import curvaabc.controller.ProdutoController;
import curvaabc.model.Produto;
import java.awt.Window;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allan
 */
public class GerenciarProdutosView extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarProdutos
     */
    public GerenciarProdutosView() throws SQLException {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        ProdutoController p_controller = new ProdutoController();
        preencherTabela(p_controller);
    }
    
    // Arrendondamento
    public static double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();

        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }

    
    //Preenche a tabela de acordo com um arraylist
    public void preencherTabela(ProdutoController p_controller){
        
        // Cria o modelo da tabela e define como ordenável
        DefaultTableModel model = (DefaultTableModel) tabelaGerenciar.getModel();
        
        model.setRowCount(0);
        tabelaGerenciar.setAutoCreateRowSorter(true);
        
        // Centraliza o texto
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < 4; i++) tabelaGerenciar.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
        
        // Inicializa a lista de produtos
        ArrayList<Produto> produtos = p_controller.getProdutos();
        
        
        for (int i = 0; i < produtos.size(); i++){
            
            // Instancia o produto da vez
            Produto p = produtos.get(i);
            
            // Insere na tabela
            model.insertRow(tabelaGerenciar.getRowCount(), new Object[] {p.getId(), p.getPreco(), p.getVendidos(), p.getCriticidade()});
            
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaGerenciar = new javax.swing.JTable();
        button_adicionar = new javax.swing.JButton();
        button_editar = new javax.swing.JButton();
        button_remover = new javax.swing.JButton();
        button_atualizar = new javax.swing.JButton();
        button_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaGerenciar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Valor unitário", "Qtd. Média Vendida", "Criticidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaGerenciar);

        button_adicionar.setText("Adicionar...");
        button_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_adicionarMouseClicked(evt);
            }
        });

        button_editar.setText("Editar");
        button_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_editarMouseClicked(evt);
            }
        });

        button_remover.setText("Remover");
        button_remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_removerMouseClicked(evt);
            }
        });

        button_atualizar.setText("Atualizar");
        button_atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_atualizarMouseClicked(evt);
            }
        });

        button_fechar.setText("Fechar");
        button_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_fecharMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Gerenciar Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button_adicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_remover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_atualizar))
                            .addComponent(button_fechar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_adicionar)
                    .addComponent(button_editar)
                    .addComponent(button_remover)
                    .addComponent(button_atualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_fechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_adicionarMouseClicked
        AddProdutoView t = null;
        try {
            t = new AddProdutoView();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InicioView.class.getName()).log(Level.SEVERE, null, ex);
        }
            Window w = new Window(t);
            t.setVisible(true);
    }//GEN-LAST:event_button_adicionarMouseClicked

    private void button_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_editarMouseClicked
       AddProdutoView t = null;
            int selectedRow = tabelaGerenciar.getSelectedRow();
        try {
            t = new AddProdutoView(selectedRow);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InicioView.class.getName()).log(Level.SEVERE, null, ex);
        }
            Window w = new Window(t);
            t.setVisible(true);
    }//GEN-LAST:event_button_editarMouseClicked

    private void button_removerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_removerMouseClicked
        int selectedRow = tabelaGerenciar.getSelectedRow();
        Produto p = new Produto();
        
        p.setId((tabelaGerenciar.getValueAt(selectedRow, 0)).toString());
        
        try {
            ConexaoDB.removerProduto(GerenciarProdutosView.this, p);
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarProdutosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_removerMouseClicked

    private void button_atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_atualizarMouseClicked
        ProdutoController p_controller = null;
        try {
            p_controller = new ProdutoController();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarProdutosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        preencherTabela(p_controller);
    }//GEN-LAST:event_button_atualizarMouseClicked

    private void button_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_fecharMouseClicked
         this.dispose();
    }//GEN-LAST:event_button_fecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GerenciarProdutosView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GerenciarProdutosView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_adicionar;
    private javax.swing.JButton button_atualizar;
    private javax.swing.JButton button_editar;
    private javax.swing.JButton button_fechar;
    private javax.swing.JButton button_remover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabelaGerenciar;
    // End of variables declaration//GEN-END:variables
}
